name: Fetch Fallout 76 Nuke Codes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: go mod tidy

      - name: Run the Go program
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }} # Use the secret from GitHub Actions
        run: |
          go run main.go
